
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtngPessoa = new javax.swing.ButtonGroup();
        BtngSexo = new javax.swing.ButtonGroup();
        LblCodigo = new javax.swing.JLabel();
        JtfCodigo = new javax.swing.JTextField();
        LblNome = new javax.swing.JLabel();
        JtfNome = new javax.swing.JTextField();
        LblEndereco = new javax.swing.JLabel();
        JtfEndereco = new javax.swing.JTextField();
        LblTelefone = new javax.swing.JLabel();
        JtfTelefone = new javax.swing.JTextField();
        LblBairro = new javax.swing.JLabel();
        JtfBairro = new javax.swing.JTextField();
        LblNumero = new javax.swing.JLabel();
        JtfNumero = new javax.swing.JTextField();
        LblComplemento = new javax.swing.JLabel();
        JtfComplemento = new javax.swing.JTextField();
        LblEstado = new javax.swing.JLabel();
        JcbEstado = new javax.swing.JComboBox<>();
        LblCidade = new javax.swing.JLabel();
        JtfCidade = new javax.swing.JTextField();
        LblCEP = new javax.swing.JLabel();
        JtfCEP = new javax.swing.JTextField();
        LblPessoa = new javax.swing.JLabel();
        RbtnFisica = new javax.swing.JRadioButton();
        RbtnJuridica = new javax.swing.JRadioButton();
        LblRG = new javax.swing.JLabel();
        JtfRG = new javax.swing.JTextField();
        LblCPF = new javax.swing.JLabel();
        JtfCPF = new javax.swing.JTextField();
        LblCNPJ = new javax.swing.JLabel();
        JtfCNPJ = new javax.swing.JTextField();
        LblIncricao = new javax.swing.JLabel();
        JtfInscricao = new javax.swing.JTextField();
        LblSexo = new javax.swing.JLabel();
        RbtnFeminino = new javax.swing.JRadioButton();
        RbtnMasculino = new javax.swing.JRadioButton();
        LblEstadoCivil = new javax.swing.JLabel();
        JtfEstadoCivil = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        BtnIncluir = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCodigo.setText("Codigo");

        LblNome.setText("Nome");

        LblEndereco.setText("Endereco");

        LblTelefone.setText("Telefone");

        LblBairro.setText("Bairro ");

        LblNumero.setText("Numero");

        LblComplemento.setText("Complemento");

        LblEstado.setText("Estado");

        JcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL ", "AP ", "AM", "BA ", "CE ", "DF ", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR ", "PE ", "PI", "RR ", "RO ", "RJ ", "RN", "RS ", "SC ", "SP ", "SE ", "TO" }));

        LblCidade.setText("Cidade");

        LblCEP.setText("CEP");

        LblPessoa.setText("Pessoa");

        BtngPessoa.add(RbtnFisica);
        RbtnFisica.setText("Fisica");

        BtngPessoa.add(RbtnJuridica);
        RbtnJuridica.setText("Juridica");

        LblRG.setText("RG");

        JtfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfRGActionPerformed(evt);
            }
        });

        LblCPF.setText("CPF");

        LblCNPJ.setText("CNPJ");

        JtfCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfCNPJActionPerformed(evt);
            }
        });

        LblIncricao.setText("Incrição estadual");

        LblSexo.setText("Sexo");

        BtngSexo.add(RbtnFeminino);
        RbtnFeminino.setText("Feminino");
        RbtnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnFemininoActionPerformed(evt);
            }
        });

        BtngSexo.add(RbtnMasculino);
        RbtnMasculino.setText("Masculino");

        LblEstadoCivil.setText("Estado civil");

        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        BtnIncluir.setText("Incluir");
        BtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIncluirActionPerformed(evt);
            }
        });

        BtnListar.setText("Listar");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Endereço", "Telefone", "Bairro", "Numero", "Complemento", "Estado", "Cidade", "CEP", "Pessoa", "RG", "CPF", "CNPJ", "Inscrição estadual", "Sexo", "Estado Civil"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LblEstado)
                                .addGap(18, 18, 18)
                                .addComponent(LblCidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblBairro))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblNumero)
                                    .addComponent(JtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LblPessoa)
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblRG))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LblComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(JtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RbtnFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RbtnFeminino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RbtnMasculino)
                                    .addGap(18, 18, 18)
                                    .addComponent(JtfEstadoCivil))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LblSexo)
                                    .addGap(137, 137, 137)
                                    .addComponent(LblEstadoCivil))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LblCNPJ)
                                        .addComponent(RbtnJuridica))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LblIncricao)
                                                .addComponent(JtfInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(114, 114, 114)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LblCPF)
                                                .addComponent(JtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LblCEP)))))))
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BtnLimpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSair))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnListar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnExcluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnIncluir)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblCodigo)
                                .addComponent(JtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblNome)
                                .addComponent(JtfNome)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblEndereco))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblTelefone)
                                .addComponent(JtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCodigo)
                    .addComponent(LblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEndereco)
                    .addComponent(LblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBairro)
                    .addComponent(LblNumero)
                    .addComponent(LblComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEstado)
                    .addComponent(LblCidade)
                    .addComponent(LblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPessoa)
                    .addComponent(LblRG)
                    .addComponent(LblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnFisica)
                    .addComponent(RbtnJuridica)
                    .addComponent(JtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCNPJ)
                    .addComponent(LblIncricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSexo)
                    .addComponent(LblEstadoCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnFeminino)
                    .addComponent(RbtnMasculino)
                    .addComponent(JtfEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIncluir)
                    .addComponent(BtnListar)
                    .addComponent(BtnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSair)
                    .addComponent(BtnLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfRGActionPerformed

    private void JtfCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfCNPJActionPerformed

    private void RbtnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnFemininoActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Deseja limpar os dados?", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION)
        {
            JtfCodigo.setText("");
            JtfNome.setText("");
            JtfTelefone.setText("");
            JtfEndereco.setText("");
            JtfBairro.setText("");
            JtfNumero.setText("");
            JtfComplemento.setText("");
            JcbEstado.setSelectedItem("AC");
            JtfCidade.setText("");
            JtfCEP.setText("");
            RbtnFisica.setSelected(false);
            RbtnJuridica.setSelected(false);
            JtfRG.setText("");
            JtfCPF.setText("");
            JtfCNPJ.setText("");
            JtfInscricao.setText("");
            RbtnFeminino.setSelected(false);
            RbtnMasculino.setSelected(false);
            JtfEstadoCivil.setText("");
        }
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
       DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        if(table.getSelectedRow()>=0){
            modelo.removeRow(table.getSelectedRow());
            table.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIncluirActionPerformed
       DefaultTableModel modelo = (DefaultTableModel)table.getModel();
        
        String linha[] = new String[17];
        
        linha[0] = JtfCodigo.getText();
        linha[1] = JtfNome.getText();
        linha[2] = JtfEndereco.getText();
        linha[3] = JtfTelefone.getText();
        linha[4] = JtfBairro.getText();
        linha[5] = JtfNumero.getText();
        linha[6] = JtfComplemento.getText();
        linha[7] = JcbEstado.getSelectedItem().toString();
        linha[8] = JtfCidade.getText();
        linha[9] = JtfCEP.getText();
        linha[10] = (RbtnFisica.isSelected())?"Fisica":"Juridica";
        linha[11] = JtfRG.getText();
        linha[12] = JtfCPF.getText();
        linha[13] = JtfCNPJ.getText();
        linha[14] = JtfInscricao.getText();
        linha[15] = (RbtnFeminino.isSelected())?"Feminino":"Masculino";
        linha[16] = JtfEstadoCivil.getText();
        
        modelo.addRow(linha);
        JtfCodigo.setText("");
        JtfNome.setText("");
        JtfTelefone.setText("");
        JtfEndereco.setText("");
        JtfBairro.setText("");
        JtfNumero.setText("");
        JtfComplemento.setText("");
        JcbEstado.setSelectedItem("AC");
        JtfCidade.setText("");
        JtfCEP.setText("");
        RbtnFisica.setSelected(false);
        RbtnJuridica.setSelected(false);
        JtfRG.setText("");
        JtfCPF.setText("");
        JtfCNPJ.setText("");
        JtfInscricao.setText("");
        RbtnFeminino.setSelected(false);
        RbtnMasculino.setSelected(false);
        JtfEstadoCivil.setText("");
    }//GEN-LAST:event_BtnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnIncluir;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnSair;
    private javax.swing.ButtonGroup BtngPessoa;
    private javax.swing.ButtonGroup BtngSexo;
    private javax.swing.JComboBox<String> JcbEstado;
    private javax.swing.JTextField JtfBairro;
    private javax.swing.JTextField JtfCEP;
    private javax.swing.JTextField JtfCNPJ;
    private javax.swing.JTextField JtfCPF;
    private javax.swing.JTextField JtfCidade;
    private javax.swing.JTextField JtfCodigo;
    private javax.swing.JTextField JtfComplemento;
    private javax.swing.JTextField JtfEndereco;
    private javax.swing.JTextField JtfEstadoCivil;
    private javax.swing.JTextField JtfInscricao;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JTextField JtfNumero;
    private javax.swing.JTextField JtfRG;
    private javax.swing.JTextField JtfTelefone;
    private javax.swing.JLabel LblBairro;
    private javax.swing.JLabel LblCEP;
    private javax.swing.JLabel LblCNPJ;
    private javax.swing.JLabel LblCPF;
    private javax.swing.JLabel LblCidade;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblComplemento;
    private javax.swing.JLabel LblEndereco;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblEstadoCivil;
    private javax.swing.JLabel LblIncricao;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblNumero;
    private javax.swing.JLabel LblPessoa;
    private javax.swing.JLabel LblRG;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTelefone;
    private javax.swing.JRadioButton RbtnFeminino;
    private javax.swing.JRadioButton RbtnFisica;
    private javax.swing.JRadioButton RbtnJuridica;
    private javax.swing.JRadioButton RbtnMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
